# Generated by Django 4.2.27 on 2025-12-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Environment', 'Environment'), ('Education/Library', 'Education/Library'), ('Healthcare', 'Healthcare'), ('Government', 'Government'), ('Food & Hunger', 'Food & Hunger'), ('Elder Care', 'Elder Care'), ('Sports & Recreation', 'Sports & Recreation'), ('Town Square Events', 'Town Square Events')], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='volunteerprofile',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='volunteerprofile',
            name='is_active',
        ),
    ]
