# Generated by Django 4.2.27 on 2026-04-16 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('volunteers', '0007_organization_notify_on_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_type',
            field=models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], default='internal', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='external_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ExternalRegistrationClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_clicks', to='volunteers.event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-clicked_at'],
            },
        ),
    ]
