# Matthew Li
# Generated by Django 4.2.27 on 2026-04-16 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0008_event_registration_type_and_click_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Environment', 'Environment'), ('Education/Library', 'Education/Library'), ('Healthcare', 'Healthcare'), ('Government', 'Government'), ('Food & Hunger', 'Food & Hunger'), ('Senior Center', 'Senior Center'), ('Physical Wellness', 'Physical Wellness'), ('Town Square Events', 'Town Square Events'), ('Animal Care', 'Animal Care')], max_length=50),
        ),
    ]
